export function DisclaimerContent() {
  return (
    <div className="space-y-6 text-foreground [&_h2]:text-2xl [&_h2]:font-bold [&_h2]:mt-8 [&_h2]:mb-4 [&_ul]:list-disc [&_ul]:pl-6 [&_ul]:space-y-2 [&_p]:mb-4">
      <p className="text-secondary">
        By installing, accessing, or using SirBro, you confirm that you have read, understood, and agreed to all the terms, policies, and conditions described in this document.
      </p>

      <h2>1. No Gambling or Betting</h2>
      <p>SirBro does not offer, promote, or facilitate gambling, betting, or wagering of any kind. The app is designed solely for informational and entertainment purposes.</p>
      <p>We do not accept bets, process payments for betting, or provide links to gambling platforms.</p>

      <h2>2. Entertainment Only</h2>
      <p>All predictions, insights, statistics, and AI-generated content provided by SirBro are for entertainment and informational purposes only.</p>
      <p>SirBro does not guarantee the accuracy, completeness, or reliability of any information provided. Users should not rely on this information for making financial or betting decisions.</p>

      <h2>3. AI-Generated Content</h2>
      <p>Content generated by AI systems may be inaccurate, incomplete, outdated, or misleading. AI models are trained on historical data and may not reflect current events or conditions.</p>
      <p>Users acknowledge that AI predictions are probabilistic estimates and should not be treated as facts or guarantees.</p>

      <h2>4. No Financial Advice</h2>
      <p>SirBro does not provide financial, investment, or betting advice. Nothing in the app should be construed as a recommendation to place bets or make financial decisions.</p>
      <p>Users are solely responsible for their own decisions and actions.</p>

      <h2>5. Third-Party Services</h2>
      <p>SirBro may display data from third-party sources (e.g., sports statistics, match results). We are not responsible for the accuracy or availability of third-party data.</p>

      <h2>6. User Responsibility</h2>
      <p>Users must comply with all applicable laws in their jurisdiction. If betting or gambling is illegal in your location, you must not use SirBro for such purposes.</p>
      <p>Users are responsible for understanding and following local regulations.</p>

      <h2>7. Age Restriction</h2>
      <p>SirBro is intended only for users aged 18 and older. By using the app, you confirm that you meet this age requirement.</p>

      <h2>8. Limitation of Liability</h2>
      <p>Levantem AI LTD shall not be liable for any losses, damages, or consequences arising from the use of SirBro, including but not limited to:</p>
      <ul>
        <li>Financial losses from betting or gambling;</li>
        <li>Inaccurate predictions or information;</li>
        <li>Service interruptions or technical issues;</li>
        <li>Third-party actions or data.</li>
      </ul>

      <h2>9. Changes to This Disclaimer</h2>
      <p>We may update this Disclaimer at any time. Continued use of the app after changes means you accept the updated Disclaimer.</p>

      <h2>10. Contact</h2>
      <p>For questions about this Disclaimer: legal@levantemai.pro</p>
      <p>For general support: support@levantemai.pro</p>

      <p className="mt-8 text-secondary">© 2025 Levantem AI LTD. All rights reserved.</p>
    </div>
  );
}
